composio_task:
  description: >
    Understand the user's needs and assist them with their needs: {user_input}
  expected_output: >
   Summary of the user's needs and how you will assist them.
  agent: composio_agent


